# Generated by Django 6.0.5 on 2026-06-11 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_video_duration_video_file_size_video_resolution_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='moderation_report',
            field=models.TextField(blank=True, default='{}'),
        ),
        migrations.AddField(
            model_name='video',
            name='moderation_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('allowed', 'Allowed'), ('flagged', 'Flagged'), ('rejected', 'Rejected'), ('manual_review', 'Manual Review')], default='pending', max_length=20),
        ),
    ]
